server:
  port: 8761

spring:
  application:
    name: spring-cloud-sample-eureka-server

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server:port}/eureka
#    registerWithEureka: false
#    fetchRegistry: false
#  instance:
#    hostname: localhost

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
