server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  cloud:
    loadbalancer:
      cache:
        ttl: 5
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost

#CUSTOMER-SERVICE:
#  ribbon:
#    eureka:
#      enabled: true
#    ServerListRefreshInterval: 5




