spring:
  application:
    name: CUSTOMER-SERVICE
  profiles:
    active: development
  config:
    import: configserver:http://root:admin@localhost:8888

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost
