server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost
#zuul:
#  routes:
#    order-service1:
#      path: /myorder/**
#      serviceId: order-service


spring:
  application:
    name: SPRING-CLOUD-SAMPLE-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/myorder/order/**
          filters:
            - StripPrefix=2
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/mycustomer/customer/**
          filters:
            - StripPrefix=2
